image: dockerfile/java:oracle-java8
script:
  - ./gradlew build
deploy:
  ssh:
    target: root@46.101.154.202:/root
    artifacts:
      - GITARCHIVE
    cmd: echo Done
notify:
  email:
    recipients:
      - jakob.thun@gmail.com
