image: ipaasio/java8-ci-build
script:
  - gradle build
deploy:
  ssh:
    target: core@46.101.154.202:/home/core
    artifacts:
      - build
    cmd: >
      mkdir /data &&
      rm /data/app.jar &&
      cp ./build/libs/spring-boot-camel-cxf-logging-bug.jar /data/app.jar &&
      docker run -d -name springcamelbug -v /data:/data dockerfile/java:oracle-java8 java -jar /data/app.jar 
notify:
  email:
    recipients:
      - jakob.thun@gmail.com