image: ipaasio/java8-ci-build
script:
  - gradle build
deploy:
  ssh:
    target: core@46.101.154.202:/home/core
    # copy build folder to remote
    artifacts:
      - build
    # Stop and restart app with new jar.
    cmd: >
      docker stop -t 30 springcamelbug || true &&
      docker rm springcamelbug || true &&
      mkdir -p springcamelbug-data &&
      rm -rf springcamelbug-data/app.jar &&
      cp build/libs/spring-boot-camel-cxf-logging-bug.jar springcamelbug-data/app.jar &&
      docker run -d -v /home/core/springcamelbug-data:/data -p 3333:3333 dockerfile/java:oracle-java8 java -jar /data/app.jar --name springcamelbug
  notify:
  email:
    recipients:
      - jakob.thun@gmail.com