image: dockerfile/java:oracle-java8
script:
  - ./gradlew build
deploy:
  ssh:
    target: core@46.101.154.202:/home/core
    artifacts:
      - build/libs/*.jar
    cmd: docker run -i -t -v $(ls -rt *.jar | tail --lines=1):/data/app.jar --rm dockerfile/java:oracle-java8 java -jar /data/app.jar
notify:
  email:
    recipients:
      - jakob.thun@gmail.com
