image: ipaasio/java8-ci-build
script:
  - gradle build
deploy:
  ssh:
    target: core@46.101.154.202:/home/core
    artifacts:
      - build/libs/*.jar
    cmd: ls
notify:
  email:
    recipients:
      - jakob.thun@gmail.com
#